project:
  type: website

website:
  title: "VIVIAN YOROJO MORENO"
  navbar:
    right:
      - href: index.qmd
        text: Inicio
      - href: publicaciones     
        text: Publicaciones
      - href: proyectos     
        text: Proyectos
      - href: investigacion     
        text: Investigacion
      - href: blog.html     
        text: Blog
      - href: cv.pdf     
        text: CV
      

  page-footer:
    center: "Â© Copyright 2025 Vivian Yorojo . Except where otherwise noted, all text and images licensed CC-BY-NC 4.0"

format:
  html:
    theme:
      - flatly
    css: styles.css
    toc: true



